MovieRecommender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from MovieRecommender import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls', namespace='auth')),
    path('recommender/', include('recomender.urls', namespace='recommender')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('<str:username>/', views.UserDetailView.as_view(), name='user-detail'),
]

recomender/urls.py
from django.urls import path

from . import views

app_name = 'recommender'

urlpatterns = [
    path('user_movie_list/', views.UserMovieList.as_view(), name='user_movie_list'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('recomend/', views.RecomendMovieList.as_view(), name='recomend'),
    path('movie/<slug:slug>/', views.MovieDetail.as_view(), name='movie_detail'),
    path('latest_movies', views.LatestMovieList.as_view(), name='latest_movies'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="icon" href="{% static 'images/tarantino.jpg' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
    {% endblock css %}
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}"  media="screen,projection"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bar.css' %}">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MovieRecommendations</title>
</head>

<body>
     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    {% block javascript %}
        <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
        </script>


        <script>
            $(document).ready(function(){

              // Initialize materialize data picker
              M.AutoInit();

            });
        </script>
    {% endblock javascript %}

    {% include 'header.html' %}

    <div>
        {% block content %}
        {% endblock content%}
    </div>

        <!--JavaScript at end of body for optimized loading-->
        <script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bar.js' %}"></script>
</body>

templates/header.html
<nav class="black">
    <div class="nav-wrapper">
        <a href="#" class="brand-logo right">MovieRecommendation</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            {% if user.is_authenticated %}
                <li><a class="yellow-text" href="{% url 'auth:user-detail' user.username %}">{{ user.username|capfirst }}</a></li>
                <li><a class="yellow-text" href="{% url 'recommender:user_movie_list' %}">My movies</a></li>
                <li><a class="yellow-text" href="{% url 'recommender:recomend' %}">Recommendations</a></li>
            {% else %}
                <li><a class="yellow-text" href="{% url 'auth:login' %}">Login</a></li>
            {% endif %}
            <li><a href="{% url 'recommender:latest_movies' %}">Latest Movies</a></li>
        </ul>
    </div>
</nav>